### ISSUE TITLE
New project layout

### ISSUE THREAD

**Issue by IanMayo** [debrief/python-import-library#11]
We currently have a combination of source and non-source folders at the top level of our project.

I think we should find a Python project layout standard.   Once the structure is agreed, we should refactor the project to match the new layout.

I'd like a proposal for a new project layout to be described in this document: https://docs.google.com/document/d/1fsunCg6MhjTP-EZGNpZmbh8CwKXIMjX72XGLUXJoTiY/edit#

Hopefully the proposal will link to online references/guides, to verify that we're following an established pattern.

I'd like this plan to also include a plan for the use of Python Packages, and where we require `__init__.py` files.

**Comment by BarisSari** [comment]
I've added my layout proposal and some useful information (most starred repositories, common structures, etc.) to the document.

**Comment by IanMayo** [comment]
Done.
